# //Get official jenkins images from Dockerhub: https://hub.docker.com/_/jenkins/tags
FROM jenkins/jenkins:lts

# Set user to root to install some additional software
USER root

# Setting Maven Version that needs to be installed
ENV MAVEN_VERSION 3.8.6

# Install require tools
RUN apt update; \
  apt upgrade -y; \
  apt install -y default-jre curl wget git nano; \
  apt-get clean

# Install JDK 11
RUN apt install -y openjdk-11-jdk

# Set JAVA runtime environment
ENV JAVA_HOME  /usr/lib/jvm/java-11-openjdk-amd64
ENV PATH $JAVA_HOME/bin:$PATH

# Install wget
RUN apt-get install -y wget

#get maven 8.8.6 and verify its checksum
RUN wget --no-verbose -O /tmp/apache-maven-3.8.6-bin.tar.gz 
https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz

# Install Maven and set maven runtime environment
RUN tar xzf /tmp/apache-maven-3.8.6-bin.tar.gz -C /opt/
RUN ln -s /opt/apache-maven-3.8.6 /opt/maven
RUN ln -s /opt/maven/bin/mvn /usr/local/bin
RUN rm -f /tmp/apache-maven-3.8.6-bin.tar.gz 
ENV MAVEN_HOME /opt/maven

RUN chown -R jenkins:jenkins /opt/maven

# Remove download archive files
RUN apt-get clean

USER jenkins
